spring:
  application:
    name: KnowledgeBase

  datasource:
    url: jdbc:postgresql://localhost:5432/rosgranstroy
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: knowledge_base

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
    schemas: knowledge_base
    default-schema: knowledge_base

  jackson:
    time-zone: Europe/Moscow

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: user-files

jwt:
  access-secret: bJKms382OcugiHhyeFQq09maTBikKplUReIdoNbKTlE
  refresh-secret: pbgDBKakqoxdn_MDT-13ZGH9GRpiDjAN7FOM829ArW4
  access-expiration: 900000
  refresh-expiration: 604800000